### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [sahilda/codePath_android#1]
Hello Sahil, 

Looks good, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project-based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer  learn the practical elements of Android development and best practices as quickly as possible. We also do a code review for each submitted project once the program begins.

Great to see you were able to complete some extensions to your app already. The extension tasks available on each project are often the most valuable learnings since they dive deeper into common real-world Android use cases. We encourage you to continue working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) as a way to further explore Android development. 

See if you can expand the functionality of the app or instead work on [improving the user interface](guides.codepath.com/android/Polishing-a-UI-Tips-and-Tools) by experimenting with colors, spacing, styling, icons, etc. Be sure to take a look through our [organizing your source files guide](http://guides.codepath.com/android/Organizing-your-Source-Files#android-folder-structure) for additional tips on structure as well. You can [re-submit on the application dashboard anytime](https://apply.codepath.com/dashboard/) and we'll take another look.

We'll be following up with you again shortly to outline the next steps in the admissions process.

**Comment by sahilda** [comment]
Thanks!

**Comment by codepathreview** [comment]
**PROJECT 3 FEEDBACK**

:+1: nice work. A few notes after checking out the code:

* Good work on a clean UI
* Good to see you were able to format the timestamp cleanly
* Good to see you refreshed the timeline after composing a new tweet
* Nice touch with the character count being displayed while the user composes a tweet
* Nice to see you used a SwipeRefreshLayout library for easy timeline refreshes
* Good job using RecyclerView instead of ListView
* Good job adding offline support
* Consider adding [progress bars] (http://guides.codepath.com/android/Handling-ProgressBars#actionbar-progress-bar) to your app whenever a network request goes out

Here's a detailed [Project 3 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_3_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. Hopefully by now you feel pretty comfortable with all the major pieces to basic Android apps (Views, Controllers, ActionBar, Navigation, Models, Authentication, API Communication, Persistence, et al) and see how they all fit together. We are close now to a turning point in the course where you should be hitting a "critical mass" towards your knowledge of Android. 
/cc @codepathreview

**Comment by codepathreview** [comment]
**PROJECT 4 FEEDBACK**

:+1: Decent work. A few notes after checking out the code:

* Nicely done architecting the fragments (base class and extension classes) such that you put as much code and logic as possible in the base class and then used abstract methods to define only the specific behavior where they differ
* Good to see you properly communicated the user to the user timeline fragment from the profile activity.
* Nice to see you used the ViewPager to properly setup the tabs
* Consider adding [progress bars](http://guides.codepath.com/android/Handling-ProgressBars#actionbar-progress-bar) to your app whenever a network request goes out
* Try to implement more optional features so that you will get to play with more widgets and understand complexities involved
* Considering this is 4th assignment and extension of last week's assignment, more efforts in UI polish would have been good.
* Sorry you wont be getting credit for *Implements robust error handling, check if internet is available, handle error cases, network failures* - you should be checking for network before every API call

Here's a detailed [Project 4 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_4_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you might be able to improve your submission. 

This week (Week 5), we are going to cover the last major piece to the Android puzzle and that is using the hardware and SDK components such as the camera, photo gallery, location, maps, etc. After that, Week 6 and week 7 we will be covering a few important intermediate topics such as more about styling and animation as well as testing.

Following the bootcamp, we are going to have a public demo day to celebrate the progress you've all made with our next batch of Android students and multiple companies attending to see the group projects that you all have built. We are going to help however we can over the next few weeks to get the team project apps in shape for that.  
/cc @codepathreview
